package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseArc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Arc extends BaseArc<Arc> {
	public static final Arc dao = new Arc();
}
