package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseIntersection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Intersection extends BaseIntersection<Intersection> {
	public static final Intersection dao = new Intersection();
}
