package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseLaneRelations;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LaneRelations extends BaseLaneRelations<LaneRelations> {
	public static final LaneRelations dao = new LaneRelations();
}
