package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseNodeRelations;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeRelations extends BaseNodeRelations<NodeRelations> {
	public static final NodeRelations dao = new NodeRelations();
}
