package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Node extends BaseNode<Node> {
	public static final Node dao = new Node();
}
