package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseRoadlink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roadlink extends BaseRoadlink<Roadlink> {
	public static final Roadlink dao = new Roadlink();
}
