package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseRoad;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Road extends BaseRoad<Road> {
	public static final Road dao = new Road();
}
