package com.hisense.hiatmp.himap.roadnet.model;

import com.hisense.hiatmp.himap.roadnet.model.base.BaseUtcSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UtcSection extends BaseUtcSection<UtcSection> {
	public static final UtcSection dao = new UtcSection();
}
