package com.hisense.himap.common.model;

import com.hisense.himap.common.model.base.BaseEnumType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnumType extends BaseEnumType<EnumType> {
	public static final EnumType dao = new EnumType();
}
