package com.hisense.hiatmp.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNodeRelations<M extends BaseNodeRelations<M>> extends Model<M> implements IBean {

	public void setNodeid(java.lang.String nodeid) {
		set("NODEID", nodeid);
	}

	public java.lang.String getNodeid() {
		return get("NODEID");
	}

	public void setNextNodes(java.lang.String nextNodes) {
		set("NEXT_NODES", nextNodes);
	}

	public java.lang.String getNextNodes() {
		return get("NEXT_NODES");
	}

	public void setNextArcs(java.lang.String nextArcs) {
		set("NEXT_ARCS", nextArcs);
	}

	public java.lang.String getNextArcs() {
		return get("NEXT_ARCS");
	}

	public void setArcAngles(java.lang.String arcAngles) {
		set("ARC_ANGLES", arcAngles);
	}

	public java.lang.String getArcAngles() {
		return get("ARC_ANGLES");
	}

	public void setLtztj(java.lang.String ltztj) {
		set("LTZTJ", ltztj);
	}

	public java.lang.String getLtztj() {
		return get("LTZTJ");
	}

	public void setCreateOperator(java.lang.String createOperator) {
		set("CREATE_OPERATOR", createOperator);
	}

	public java.lang.String getCreateOperator() {
		return get("CREATE_OPERATOR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdateOperator(java.lang.String updateOperator) {
		set("UPDATE_OPERATOR", updateOperator);
	}

	public java.lang.String getUpdateOperator() {
		return get("UPDATE_OPERATOR");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

}
