package com.hisense.hiatmp.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArc<M extends BaseArc<M>> extends Model<M> implements IBean {

	public void setArcid(java.lang.String arcid) {
		set("ARCID", arcid);
	}

	public java.lang.String getArcid() {
		return get("ARCID");
	}

	public void setArcname(java.lang.String arcname) {
		set("ARCNAME", arcname);
	}

	public java.lang.String getArcname() {
		return get("ARCNAME");
	}

	public void setArclength(java.math.BigDecimal arclength) {
		set("ARCLENGTH", arclength);
	}

	public java.math.BigDecimal getArclength() {
		return get("ARCLENGTH");
	}

	public void setStartnode(java.lang.String startnode) {
		set("STARTNODE", startnode);
	}

	public java.lang.String getStartnode() {
		return get("STARTNODE");
	}

	public void setEndnode(java.lang.String endnode) {
		set("ENDNODE", endnode);
	}

	public java.lang.String getEndnode() {
		return get("ENDNODE");
	}

	public void setStrcoords(java.lang.String strcoords) {
		set("STRCOORDS", strcoords);
	}

	public java.lang.String getStrcoords() {
		return get("STRCOORDS");
	}

	public void setRoadcode(java.lang.String roadcode) {
		set("ROADCODE", roadcode);
	}

	public java.lang.String getRoadcode() {
		return get("ROADCODE");
	}

	public void setGeometry(java.lang.String geometry) {
		set("GEOMETRY", geometry);
	}

	public java.lang.String getGeometry() {
		return get("GEOMETRY");
	}

	public void setCreateOperator(java.lang.String createOperator) {
		set("CREATE_OPERATOR", createOperator);
	}

	public java.lang.String getCreateOperator() {
		return get("CREATE_OPERATOR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdateOperator(java.lang.String updateOperator) {
		set("UPDATE_OPERATOR", updateOperator);
	}

	public java.lang.String getUpdateOperator() {
		return get("UPDATE_OPERATOR");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

	public void setArctype(java.lang.String arctype) {
		set("ARCTYPE", arctype);
	}

	public java.lang.String getArctype() {
		return get("ARCTYPE");
	}

	public void setTrafficDir(java.lang.String trafficDir) {
		set("TRAFFIC_DIR", trafficDir);
	}

	public java.lang.String getTrafficDir() {
		return get("TRAFFIC_DIR");
	}

}
