package com.hisense.hiatmp.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLane<M extends BaseLane<M>> extends Model<M> implements IBean {

	public void setLaneno(java.lang.String laneno) {
		set("LANENO", laneno);
	}

	public java.lang.String getLaneno() {
		return get("LANENO");
	}

	public void setDirection(java.math.BigDecimal direction) {
		set("DIRECTION", direction);
	}

	public java.math.BigDecimal getDirection() {
		return get("DIRECTION");
	}

	public void setLanetype(java.lang.String lanetype) {
		set("LANETYPE", lanetype);
	}

	public java.lang.String getLanetype() {
		return get("LANETYPE");
	}

	public void setSsld(java.lang.String ssld) {
		set("SSLD", ssld);
	}

	public java.lang.String getSsld() {
		return get("SSLD");
	}

	public void setSslk(java.lang.String sslk) {
		set("SSLK", sslk);
	}

	public java.lang.String getSslk() {
		return get("SSLK");
	}

	public void setQd(java.math.BigDecimal qd) {
		set("QD", qd);
	}

	public java.math.BigDecimal getQd() {
		return get("QD");
	}

	public void setZd(java.math.BigDecimal zd) {
		set("ZD", zd);
	}

	public java.math.BigDecimal getZd() {
		return get("ZD");
	}

	public void setCreateOperator(java.lang.String createOperator) {
		set("CREATE_OPERATOR", createOperator);
	}

	public java.lang.String getCreateOperator() {
		return get("CREATE_OPERATOR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdateOperator(java.lang.String updateOperator) {
		set("UPDATE_OPERATOR", updateOperator);
	}

	public java.lang.String getUpdateOperator() {
		return get("UPDATE_OPERATOR");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

}
