package com.hisense.hiatmp.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoad<M extends BaseRoad<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("UUID", uuid);
	}

	public java.lang.String getUuid() {
		return get("UUID");
	}

	public void setDldm(java.lang.String dldm) {
		set("DLDM", dldm);
	}

	public java.lang.String getDldm() {
		return get("DLDM");
	}

	public void setDlmc(java.lang.String dlmc) {
		set("DLMC", dlmc);
	}

	public java.lang.String getDlmc() {
		return get("DLMC");
	}

	public void setBmdm(java.lang.String bmdm) {
		set("BMDM", bmdm);
	}

	public java.lang.String getBmdm() {
		return get("BMDM");
	}

	public void setXzqh(java.lang.String xzqh) {
		set("XZQH", xzqh);
	}

	public java.lang.String getXzqh() {
		return get("XZQH");
	}

	public void setDllx(java.lang.String dllx) {
		set("DLLX", dllx);
	}

	public java.lang.String getDllx() {
		return get("DLLX");
	}

	public void setGlxzdj(java.lang.String glxzdj) {
		set("GLXZDJ", glxzdj);
	}

	public java.lang.String getGlxzdj() {
		return get("GLXZDJ");
	}

	public void setDx(java.lang.String dx) {
		set("DX", dx);
	}

	public java.lang.String getDx() {
		return get("DX");
	}

	public void setDlxx(java.lang.String dlxx) {
		set("DLXX", dlxx);
	}

	public java.lang.String getDlxx() {
		return get("DLXX");
	}

	public void setLkldlx(java.lang.String lkldlx) {
		set("LKLDLX", lkldlx);
	}

	public java.lang.String getLkldlx() {
		return get("LKLDLX");
	}

	public void setDlwlgl(java.lang.String dlwlgl) {
		set("DLWLGL", dlwlgl);
	}

	public java.lang.String getDlwlgl() {
		return get("DLWLGL");
	}

	public void setLmjg(java.lang.String lmjg) {
		set("LMJG", lmjg);
	}

	public java.lang.String getLmjg() {
		return get("LMJG");
	}

	public void setFhsslx(java.lang.String fhsslx) {
		set("FHSSLX", fhsslx);
	}

	public java.lang.String getFhsslx() {
		return get("FHSSLX");
	}

	public void setQs(java.math.BigDecimal qs) {
		set("QS", qs);
	}

	public java.math.BigDecimal getQs() {
		return get("QS");
	}

	public void setJs(java.math.BigDecimal js) {
		set("JS", js);
	}

	public java.math.BigDecimal getJs() {
		return get("JS");
	}

	public void setXqlc(java.math.BigDecimal xqlc) {
		set("XQLC", xqlc);
	}

	public java.math.BigDecimal getXqlc() {
		return get("XQLC");
	}

	public void setCjr(java.lang.String cjr) {
		set("CJR", cjr);
	}

	public java.lang.String getCjr() {
		return get("CJR");
	}

	public void setCjsj(java.util.Date cjsj) {
		set("CJSJ", cjsj);
	}

	public java.util.Date getCjsj() {
		return get("CJSJ");
	}

	public void setGxr(java.lang.String gxr) {
		set("GXR", gxr);
	}

	public java.lang.String getGxr() {
		return get("GXR");
	}

	public void setGxsj(java.util.Date gxsj) {
		set("GXSJ", gxsj);
	}

	public java.util.Date getGxsj() {
		return get("GXSJ");
	}

	public void setJlzt(java.lang.String jlzt) {
		set("JLZT", jlzt);
	}

	public java.lang.String getJlzt() {
		return get("JLZT");
	}

	public void setQsmc(java.lang.String qsmc) {
		set("QSMC", qsmc);
	}

	public java.lang.String getQsmc() {
		return get("QSMC");
	}

	public void setXzqhxxlc(java.lang.String xzqhxxlc) {
		set("XZQHXXLC", xzqhxxlc);
	}

	public java.lang.String getXzqhxxlc() {
		return get("XZQHXXLC");
	}

	public void setZyglss(java.lang.String zyglss) {
		set("ZYGLSS", zyglss);
	}

	public java.lang.String getZyglss() {
		return get("ZYGLSS");
	}

	public void setSsglbm(java.lang.String ssglbm) {
		set("SSGLBM", ssglbm);
	}

	public java.lang.String getSsglbm() {
		return get("SSGLBM");
	}

	public void setBzdllx(java.lang.String bzdllx) {
		set("BZDLLX", bzdllx);
	}

	public java.lang.String getBzdllx() {
		return get("BZDLLX");
	}

	public void setBbh(java.lang.String bbh) {
		set("BBH", bbh);
	}

	public java.lang.String getBbh() {
		return get("BBH");
	}

}
