package com.hisense.hiatmp.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJoinpoint<M extends BaseJoinpoint<M>> extends Model<M> implements IBean {

	public void setPointid(java.lang.String pointid) {
		set("POINTID", pointid);
	}

	public java.lang.String getPointid() {
		return get("POINTID");
	}

	public void setStrcoords(java.lang.String strcoords) {
		set("STRCOORDS", strcoords);
	}

	public java.lang.String getStrcoords() {
		return get("STRCOORDS");
	}

	public void setCrossArcs(java.lang.String crossArcs) {
		set("CROSS_ARCS", crossArcs);
	}

	public java.lang.String getCrossArcs() {
		return get("CROSS_ARCS");
	}

	public void setGeometry(java.lang.String geometry) {
		set("GEOMETRY", geometry);
	}

	public java.lang.String getGeometry() {
		return get("GEOMETRY");
	}

	public void setCreateOperator(java.lang.String createOperator) {
		set("CREATE_OPERATOR", createOperator);
	}

	public java.lang.String getCreateOperator() {
		return get("CREATE_OPERATOR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdateOperator(java.lang.String updateOperator) {
		set("UPDATE_OPERATOR", updateOperator);
	}

	public java.lang.String getUpdateOperator() {
		return get("UPDATE_OPERATOR");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

}
