package com.hisense.hiatmp.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUtcSection<M extends BaseUtcSection<M>> extends Model<M> implements IBean {

	public void setSectionid(java.lang.String sectionid) {
		set("SECTIONID", sectionid);
	}

	public java.lang.String getSectionid() {
		return get("SECTIONID");
	}

	public void setSectionname(java.lang.String sectionname) {
		set("SECTIONNAME", sectionname);
	}

	public java.lang.String getSectionname() {
		return get("SECTIONNAME");
	}

	public void setUppints(java.lang.String uppints) {
		set("UPPINTS", uppints);
	}

	public java.lang.String getUppints() {
		return get("UPPINTS");
	}

	public void setDownints(java.lang.String downints) {
		set("DOWNINTS", downints);
	}

	public java.lang.String getDownints() {
		return get("DOWNINTS");
	}

	public void setRoadCode(java.lang.String roadCode) {
		set("ROAD_CODE", roadCode);
	}

	public java.lang.String getRoadCode() {
		return get("ROAD_CODE");
	}

	public void setWidth(java.math.BigDecimal width) {
		set("WIDTH", width);
	}

	public java.math.BigDecimal getWidth() {
		return get("WIDTH");
	}

	public void setLength(java.math.BigDecimal length) {
		set("LENGTH", length);
	}

	public java.math.BigDecimal getLength() {
		return get("LENGTH");
	}

	public void setDirection(java.math.BigDecimal direction) {
		set("DIRECTION", direction);
	}

	public java.math.BigDecimal getDirection() {
		return get("DIRECTION");
	}

	public void setLogicDel(java.math.BigDecimal logicDel) {
		set("LOGIC_DEL", logicDel);
	}

	public java.math.BigDecimal getLogicDel() {
		return get("LOGIC_DEL");
	}

	public void setRoadLevel(java.math.BigDecimal roadLevel) {
		set("ROAD_LEVEL", roadLevel);
	}

	public java.math.BigDecimal getRoadLevel() {
		return get("ROAD_LEVEL");
	}

	public void setFireespeed(java.math.BigDecimal fireespeed) {
		set("FIREESPEED", fireespeed);
	}

	public java.math.BigDecimal getFireespeed() {
		return get("FIREESPEED");
	}

	public void setRyspeed(java.math.BigDecimal ryspeed) {
		set("RYSPEED", ryspeed);
	}

	public java.math.BigDecimal getRyspeed() {
		return get("RYSPEED");
	}

	public void setYgspeed(java.math.BigDecimal ygspeed) {
		set("YGSPEED", ygspeed);
	}

	public java.math.BigDecimal getYgspeed() {
		return get("YGSPEED");
	}

	public void setHotpressure(java.lang.String hotpressure) {
		set("HOTPRESSURE", hotpressure);
	}

	public java.lang.String getHotpressure() {
		return get("HOTPRESSURE");
	}

	public void setNorpressure(java.lang.String norpressure) {
		set("NORPRESSURE", norpressure);
	}

	public java.lang.String getNorpressure() {
		return get("NORPRESSURE");
	}

	public void setLowpressure(java.lang.String lowpressure) {
		set("LOWPRESSURE", lowpressure);
	}

	public java.lang.String getLowpressure() {
		return get("LOWPRESSURE");
	}

	public void setArcs(java.lang.String arcs) {
		set("ARCS", arcs);
	}

	public java.lang.String getArcs() {
		return get("ARCS");
	}

	public void setOppSection(java.lang.String oppSection) {
		set("OPP_SECTION", oppSection);
	}

	public java.lang.String getOppSection() {
		return get("OPP_SECTION");
	}

	public void setCreateOperator(java.lang.String createOperator) {
		set("CREATE_OPERATOR", createOperator);
	}

	public java.lang.String getCreateOperator() {
		return get("CREATE_OPERATOR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdateOperator(java.lang.String updateOperator) {
		set("UPDATE_OPERATOR", updateOperator);
	}

	public java.lang.String getUpdateOperator() {
		return get("UPDATE_OPERATOR");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

	public void setSections(java.lang.String sections) {
		set("SECTIONS", sections);
	}

	public java.lang.String getSections() {
		return get("SECTIONS");
	}

}
