package com.hisense.hiatmp.himap.common.model;

import com.hisense.hiatmp.himap.common.model.base.BaseSysparams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sysparams extends BaseSysparams<Sysparams> {
	public static final Sysparams dao = new Sysparams();
}
