package com.hisense.hiatmp.himap.mapindex.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: LID,LID
		arp.addMapping("LAYER_TYPE", "LID", LayerType.class);
		// Composite Primary Key order: LAYERID,LAYERID,USERID,USERID
		arp.addMapping("USER_FAVOR_LAYER", "LAYERID,USERID", UserFavorLayer.class);
	}
}

