package com.hisense.hiatmp.himap.mapindex.model;

import com.hisense.hiatmp.himap.mapindex.model.base.BaseLayerType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LayerType extends BaseLayerType<LayerType> {
	public static final LayerType dao = new LayerType();
}
