package com.hisense.hiatmp.himap.mapindex.model;

import com.hisense.hiatmp.himap.mapindex.model.base.BaseUserFavorLayer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFavorLayer extends BaseUserFavorLayer<UserFavorLayer> {
	public static final UserFavorLayer dao = new UserFavorLayer();
}
