package com.hisense.hiatmp.himap.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEnumType<M extends BaseEnumType<M>> extends Model<M> implements IBean {

	public void setEnumtypeid(java.math.BigDecimal enumtypeid) {
		set("ENUMTYPEID", enumtypeid);
	}

	public java.math.BigDecimal getEnumtypeid() {
		return get("ENUMTYPEID");
	}

	public void setEnumvalue(java.lang.String enumvalue) {
		set("ENUMVALUE", enumvalue);
	}

	public java.lang.String getEnumvalue() {
		return get("ENUMVALUE");
	}

	public void setEnumname(java.lang.String enumname) {
		set("ENUMNAME", enumname);
	}

	public java.lang.String getEnumname() {
		return get("ENUMNAME");
	}

	public void setIsdefault(java.math.BigDecimal isdefault) {
		set("ISDEFAULT", isdefault);
	}

	public java.math.BigDecimal getIsdefault() {
		return get("ISDEFAULT");
	}

	public void setDispindex(java.math.BigDecimal dispindex) {
		set("DISPINDEX", dispindex);
	}

	public java.math.BigDecimal getDispindex() {
		return get("DISPINDEX");
	}

	public void setValid(java.math.BigDecimal valid) {
		set("VALID", valid);
	}

	public java.math.BigDecimal getValid() {
		return get("VALID");
	}

}
