package com.hisense.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntersection<M extends BaseIntersection<M>> extends Model<M> implements IBean {

	public void setIntsid(java.lang.String intsid) {
		set("INTSID", intsid);
	}

	public java.lang.String getIntsid() {
		return get("INTSID");
	}

	public void setDldm(java.lang.String dldm) {
		set("DLDM", dldm);
	}

	public java.lang.String getDldm() {
		return get("DLDM");
	}

	public void setLkdm(java.lang.String lkdm) {
		set("LKDM", lkdm);
	}

	public java.lang.String getLkdm() {
		return get("LKDM");
	}

	public void setLkmc(java.lang.String lkmc) {
		set("LKMC", lkmc);
	}

	public java.lang.String getLkmc() {
		return get("LKMC");
	}

	public void setBmdm(java.lang.String bmdm) {
		set("BMDM", bmdm);
	}

	public java.lang.String getBmdm() {
		return get("BMDM");
	}

	public void setIntstype(java.math.BigDecimal intstype) {
		set("INTSTYPE", intstype);
	}

	public java.math.BigDecimal getIntstype() {
		return get("INTSTYPE");
	}

	public void setLongitude(java.lang.String longitude) {
		set("LONGITUDE", longitude);
	}

	public java.lang.String getLongitude() {
		return get("LONGITUDE");
	}

	public void setLatitude(java.lang.String latitude) {
		set("LATITUDE", latitude);
	}

	public java.lang.String getLatitude() {
		return get("LATITUDE");
	}

	public void setCjr(java.lang.String cjr) {
		set("CJR", cjr);
	}

	public java.lang.String getCjr() {
		return get("CJR");
	}

	public void setCjsj(java.util.Date cjsj) {
		set("CJSJ", cjsj);
	}

	public java.util.Date getCjsj() {
		return get("CJSJ");
	}

	public void setGxr(java.lang.String gxr) {
		set("GXR", gxr);
	}

	public java.lang.String getGxr() {
		return get("GXR");
	}

	public void setGxsj(java.util.Date gxsj) {
		set("GXSJ", gxsj);
	}

	public java.util.Date getGxsj() {
		return get("GXSJ");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

	public void setNodeid(java.lang.String nodeid) {
		set("NODEID", nodeid);
	}

	public java.lang.String getNodeid() {
		return get("NODEID");
	}

}
