package com.hisense.himap.roadnet.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLaneRelations<M extends BaseLaneRelations<M>> extends Model<M> implements IBean {

	public void setLaneno(java.lang.String laneno) {
		set("LANENO", laneno);
	}

	public java.lang.String getLaneno() {
		return get("LANENO");
	}

	public void setNextArc(java.lang.String nextArc) {
		set("NEXT_ARC", nextArc);
	}

	public java.lang.String getNextArc() {
		return get("NEXT_ARC");
	}

	public void setNextSection(java.lang.String nextSection) {
		set("NEXT_SECTION", nextSection);
	}

	public java.lang.String getNextSection() {
		return get("NEXT_SECTION");
	}

	public void setRelation(java.math.BigDecimal relation) {
		set("RELATION", relation);
	}

	public java.math.BigDecimal getRelation() {
		return get("RELATION");
	}

	public void setCreateOperator(java.lang.String createOperator) {
		set("CREATE_OPERATOR", createOperator);
	}

	public java.lang.String getCreateOperator() {
		return get("CREATE_OPERATOR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdateOperator(java.lang.String updateOperator) {
		set("UPDATE_OPERATOR", updateOperator);
	}

	public java.lang.String getUpdateOperator() {
		return get("UPDATE_OPERATOR");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}

	public java.lang.String getVersion() {
		return get("VERSION");
	}

}
