package com.hisense.hiatmp.himap.mapindex.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLayerType<M extends BaseLayerType<M>> extends Model<M> implements IBean {

	public void setLid(java.math.BigDecimal lid) {
		set("LID", lid);
	}

	public java.math.BigDecimal getLid() {
		return get("LID");
	}

	public void setLname(java.lang.String lname) {
		set("LNAME", lname);
	}

	public java.lang.String getLname() {
		return get("LNAME");
	}

	public void setLlevel(java.lang.String llevel) {
		set("LLEVEL", llevel);
	}

	public java.lang.String getLlevel() {
		return get("LLEVEL");
	}

	public void setLorder(java.math.BigDecimal lorder) {
		set("LORDER", lorder);
	}

	public java.math.BigDecimal getLorder() {
		return get("LORDER");
	}

	public void setLparent(java.math.BigDecimal lparent) {
		set("LPARENT", lparent);
	}

	public java.math.BigDecimal getLparent() {
		return get("LPARENT");
	}

	public void setLicon(java.lang.String licon) {
		set("LICON", licon);
	}

	public java.lang.String getLicon() {
		return get("LICON");
	}

	public void setThirdsyscode(java.lang.String thirdsyscode) {
		set("THIRDSYSCODE", thirdsyscode);
	}

	public java.lang.String getThirdsyscode() {
		return get("THIRDSYSCODE");
	}

	public void setIshidden(java.math.BigDecimal ishidden) {
		set("ISHIDDEN", ishidden);
	}

	public java.math.BigDecimal getIshidden() {
		return get("ISHIDDEN");
	}

	public void setModulename(java.lang.String modulename) {
		set("MODULENAME", modulename);
	}

	public java.lang.String getModulename() {
		return get("MODULENAME");
	}

	public void setCfunc(java.lang.String cfunc) {
		set("CFUNC", cfunc);
	}

	public java.lang.String getCfunc() {
		return get("CFUNC");
	}

	public void setUcfunc(java.lang.String ucfunc) {
		set("UCFUNC", ucfunc);
	}

	public java.lang.String getUcfunc() {
		return get("UCFUNC");
	}

}
