package com.hisense.hiatmp.himap.mapindex.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserFavorLayer<M extends BaseUserFavorLayer<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.String userid) {
		set("USERID", userid);
	}

	public java.lang.String getUserid() {
		return get("USERID");
	}

	public void setLayerid(java.math.BigDecimal layerid) {
		set("LAYERID", layerid);
	}

	public java.math.BigDecimal getLayerid() {
		return get("LAYERID");
	}

	public void setShoworder(java.math.BigDecimal showorder) {
		set("SHOWORDER", showorder);
	}

	public java.math.BigDecimal getShoworder() {
		return get("SHOWORDER");
	}

}
