package com.hisense.himap.roadnet.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ROUTE_ARC", "ARCID", Arc.class);
		arp.addMapping("ROUTE_INTERSECTION", "INTSID", Intersection.class);
		arp.addMapping("ROUTE_JOINPOINT", "POINTID", Joinpoint.class);
		arp.addMapping("ROUTE_LANE", "LANENO", Lane.class);
		arp.addMapping("ROUTE_LANE_RELATIONS", "LANENO", LaneRelations.class);
		arp.addMapping("ROUTE_NODE", "NODEID", Node.class);
		arp.addMapping("ROUTE_NODE_RELATIONS", "NODEID", NodeRelations.class);
		arp.addMapping("ROUTE_ROAD", "UUID", Road.class);
		arp.addMapping("ROUTE_ROADLINE", "UUID", Roadline.class);
		arp.addMapping("ROUTE_ROADLINK", "LINKID", Roadlink.class);
		arp.addMapping("ROUTE_SECTION", "SECTIONID", Section.class);
		arp.addMapping("ROUTE_UTC_SECTION", "SECTIONID", UtcSection.class);
	}
}

