package com.hisense.himap.roadnet.model;

import com.hisense.himap.roadnet.model.base.BaseForbiddenturn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Forbiddenturn extends BaseForbiddenturn<Forbiddenturn> {
	public static final Forbiddenturn dao = new Forbiddenturn();
}
