package com.hisense.himap.roadnet.model;

import com.hisense.himap.roadnet.model.base.BaseJoinpoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Joinpoint extends BaseJoinpoint<Joinpoint> {
	public static final Joinpoint dao = new Joinpoint();
}
