package com.hisense.himap.roadnet.model;

import com.hisense.himap.roadnet.model.base.BaseLane;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lane extends BaseLane<Lane> {
	public static final Lane dao = new Lane();
}
