package com.hisense.himap.roadnet.model;

import com.hisense.himap.roadnet.model.base.BaseRoadline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roadline extends BaseRoadline<Roadline> {
	public static final Roadline dao = new Roadline();
}
