package com.hisense.himap.roadnet.model;

import com.hisense.himap.roadnet.model.base.BaseSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Section extends BaseSection<Section> {
	public static final Section dao = new Section();
}
